# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2015-2025 Allwinner Technology Co., Ltd.
pcie_sunxi_host-objs := pcie-sunxi-rc.o pcie-sunxi-dma.o pcie-sunxi-plat.o
pcie_sunxi_ep-objs := pcie-sunxi-ep.o pcie-sunxi-dma.o pcie-sunxi-plat.o
obj-$(CONFIG_PCIE_SUNXI_RC) += pcie_sunxi_host.o
obj-$(CONFIG_PCIE_SUNXI_EP) += pcie_sunxi_ep.o
