# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PINCTRL_SUNXI_VENDOR)	+= pinctrl-sunxi.o
obj-$(CONFIG_PINCTRL_SUN60I_A733)	+= pinctrl-sun60iw2.o
obj-$(CONFIG_PINCTRL_SUN60I_A733_R)	+= pinctrl-sun60iw2-r.o
